Grace-Shopper-Team-Grapes/grapes-shopper

server/db/models/Address.js, server/db/models/user.js
Defined User and Address models including validation hooks for phone number and zip code.
=> defined User and Address models

script/Category-seed.js
New file containing category seeds made.
=> category-seed written

script/Order-seed.js, script/Product-seed.js
Forgot to branch before making product and order seed files.
=> adding order and product seeds

script/User-seed.js, server/db/models/index.js
Added alias to "Users" associations.
Created user-seed.js file.
=> changed associations and defined user seed

server/db/models/index.js
Added modules to be exported in models' index.js file.
=> exported modules in models index.js

.travis.yml, package-lock.json, script/Category-seed.js, script/Order-seed.js, script/Product-seed.js, script/seed.js, server/db/models/Category.js, server/db/models/Order.js, server/db/models/Product.js
models are now mapped in seed files. A couple 1s were made to trues.
=> Seed file improvements

script/Product-seed.js, server/api/index.js, server/api/products.js, server/db/models/Category.js, server/db/models/Product.js
=> Products API route

script/Category-seed.js, script/Order-seed.js, server/CLI testing code.txt, server/api/account.js, server/api/categories.js, server/api/index.js
get all categories
get category by slug
get all orders by user id
get a specific order of a user by order id
update phone number of user
=> Category and Account routes created

server/db/models/index.js
=> Cleaned up associations

server/db/models/Category.js, server/db/models/Product.js
Changed imageUrl from Sequelize.STRING to Sequelize.TEXT in Category.js and Product.js
=> changed imageUrl from STRING to TEXT

server/api/index.js, server/api/users.js
- Removed `/account` mounting on api/index.js
- Added `/user/:id` route
=> Begun changes to assimilate API /account route into /users

script/User-seed.js, server/db/models/index.js
*note, associations in index.js still need to be addressed at a later time.
deleted Address and OrderStatus references from db/index.js, so removed appropriate imports and exports
Cleaned up an association that was causing a cyclical error.
=> cleanup in order to run

server/db/models/Order.js, server/db/models/OrderProduct.js, server/db/models/Product.js
Before validate hooks for multiplying prices of 3 models by 100 complete.
=> Pennies validator

script/seed.js, server/api/users.spec.js, server/db/models/index.js, server/db/models/user.spec.js, server/db/tests/order.spec.js
Added tests for order model and edited user model and routes tests.
Removed redundant code in models' index.js
=> added tests for order model and edited user model and routes tests

server/db/models/Order.js, server/db/models/OrderProduct.js, server/db/models/Product.js
pennies before validate fixed with toFixed
=> pennies before validate fixed with toFixed

public/index.html, public/mockup-home.html, server/db/models/index.js
=> HTML Mockup files + Fixed Order->Product model association

server/api/index.js, server/api/orders.js, server/api/users.js
Added route to get cart items in users routes.
Changed cart.js to order.js
=> added route to get cart items in users routes

client/index.js, package-lock.json, package.json, public/mockup-home.html, public/styles/base/_base.scss, public/styles/base/_settings.scss, public/styles/components/_carousel.scss, public/styles/components/_container.scss, public/styles/components/_header.scss, public/styles/components/_logo.scss, public/styles/components/_mainNav.scss, public/styles/components/_quickLinks.scss, public/styles/components/_search.scss, public/styles/main.scss, public/styles/styles.css, webpack.config.js
=> Setup SCSS and Normalize.css

client/components/DisplayAllProducts.js, client/components/index.js, client/routes.js, client/store/index.js, client/store/products.js
displayAllProducts component on /products (frontend)
=> displayAllProducts component on localhost/products

client/index.js, package-lock.json, package.json, public/mockup-home.html, public/styles/base/_base.scss, public/styles/base/_settings.scss, public/styles/components/_carousel.scss, public/styles/components/_container.scss, public/styles/components/_header.scss, public/styles/components/_logo.scss, public/styles/components/_mainNav.scss, public/styles/components/_quickLinks.scss, public/styles/components/_search.scss, public/styles/main.scss, public/styles/styles.css, webpack.config.js
Adding styling for site homepage carousel
=> Homepage styling

client/components/DisplayAllProducts.js, client/components/DisplaySingleProduct.js, client/components/index.js, client/routes.js, client/store/index.js, client/store/singleProduct.js
Working singleProductComponent + redux
=> singleProductComponent + redux working

script/Order-seed.js, script/Product-seed.js, server/CLI testing code.txt, server/api/index.js, server/api/orders.js, server/db/models/Order.js, server/db/models/OrderProduct.js
A video to slack will be posted with demos. The first person who sees this please slack and we'll have
a Zoom meeting, because I need to make sure no merge conflicts occur.
addToCart, Checkout, and Ship are fully functional and were tested many times with curl commands.
addToCart will check inventory and then find or create orderProducts, and Order's grandtotal will be updated appropriately
Checkout does many things: It again makes sure inventory is ok, it marks items as purchased, and it adjusts the inventory of products... The many things it does...
There are many minor bug fixes fixed throughout that were discovered because I was testing functionality.
=> Add to cart,checkout,ship, and many minor bug fixes throughout due to testing

client/components/DisplayAllOrderProducts.js, client/components/DisplayAllProducts.js, client/components/DisplaySingleProduct.js, client/components/forms/AddToCart.js, client/components/forms/AddToCartForm.js, client/components/index.js, client/components/navbar.js, client/components/user-home.js, client/routes.js, client/store/index.js, client/store/orderProducts.js, client/store/singleProduct.js, script/Product-seed.js, server/api/index.js, server/api/orderProducts.js, server/api/orders.js, server/api/products.js
see most recent video demo in slack for frontend performance.
Still working on frontend cart functionality.
Minor improvements and tinkering made across the board for testing.
Merge conflicts are likely with app.js and routes.js
=> WORKING but not complete Add to cart,order products,order,checkout,components

client/components/index.js, client/components/page/Cart.js, client/components/page/Homepage.js, client/components/page/module/Carousel.js, client/components/page/module/FeaturedCategories.js, client/components/page/module/index.js, client/components/template/Header.js, client/components/template/MainNav.js, client/routes.js
- Set up site header links (quick-links and main nav) to use react-router-dom Links and NavLinks.
- Set up homepage to populate on route `/`, and filled in content.
=> Wired up homepage with React components

client/components/DisplayAllOrderProducts.js, client/components/DisplayAllProducts.js, client/components/DisplaySingleProduct.js, client/components/forms/AddToCart.js, client/components/forms/AddToCartForm.js, server/api/orderProducts.js
minor link changes and one bug fix
=> minor link changes and one bug fix

server/db/models/User.js
=> Updated User model so most fields are not required.

client/components/DisplayAllOrderProducts.js
=> Removed this.props.products bug on DisplayAllOrderProducts.js

client/components/DisplayAccountPage.js, client/components/forms/UpdateAccount.js, client/components/forms/UpdateAccountForm.js, client/routes.js, client/store/account.js, client/store/index.js, client/store/user.js, server/api/users.js, server/db/models/User.js
check most recent video from me in slack for: 
navigate to /account and you will get an account with update form hooked in redux. 
all items of user can be added, it's just tedious typing that I was too tired to do. just firstName, lastName, and e-mail for now.
Backend routes are made.
=> account beginnings working, see video in slack

client/components/DisplayAllOrderProducts.js, client/components/DisplaySingleProduct.js, client/components/forms/AddToCart.js
Cleaned up some bugs on master branch from last PR
=> Cleaned up master bugs

client/components/template/QuickLinks.js, client/store/user.js, script/User-seed.js, server/api/routeProtections.js, server/api/users.js, server/auth/index.js, server/db/models/User.js
Added route protection middleware.
Made it so "Login" link changes to "Logout".
Once logged in, user is redirected to home page. Is not able to go back to login page.
=> added route protection middleware

client/components/forms/EditCart.js, client/components/forms/EditCartForm.js, client/components/page/CartContents.js, client/store/orderProducts.js, server/api/orders.js
Lots of changes to Cart, we're getting closer! Redux store works for add to cart and textbox blur
=> That time Austin saved our lives

client/components/template/QuickLinks.js, server/auth/index.js
Adds new cart to order table upon signing up new user.
Modified quick-links "Sign-up" to be "My Account" when logged in. Links to account page.
=> adds new cart on signup

client/store/account.js, server/api/users.js
Small changes on users route to reflect changes Noelle wanted for more restful structure.
Changes had to be updated on frontend. 
@mh-393 , if you have time, check out the routes that are towards the bottom on .users and see if those are appropriate admin routes.
=> Small account changes per noelle for more restful api

client/UNUSED - helpers.js, client/components/index.js, client/components/page/AllProducts.js, client/components/page/Cart.js, client/components/page/CartContents.js, client/components/page/module/ProductGridItem.js, client/components/template/QuickLinks.js, client/routes.js, public/styles/base/_forms.scss, public/styles/components/_cart-grid.scss, public/styles/components/_cart-overlay.scss, public/styles/components/_product-grid.scss, server/api/orders.js, server/api/products.js
This one's a doozy. Let's merge this as a team. I'll try to list out the major changes I've made. Please read, there are important notes:
=> Lots of Cart, All Products, and other changes

server/CLI testing code.txt, server/api/orders.js
very small fixes. Checkout works again.
=> Debug checkout

client/components/page/Cart.js, client/components/page/CartContents.js, client/components/template/Footer.js, client/components/template/QuickLinks.js, public/styles/components/_cart-overlay.scss, public/styles/components/_footer.scss, public/styles/components/_quickLinks.scss, server/api/orders.js
- Decided to forego using react-modal
- Made tweaks to custom-made Cart modal instead
- Added event handlers to close cart modal on overlay mask click or Escape keydown
- Fixed bug where product thumbnail image wasn't showing in cart
- Footer tweaks ;-)
- Fixed Cart quick link in header to indicate number of products in cart
- Fixed cart bug where changing product qty in cart would re-order the cart list. Forced `OrderProduct.findAll()` to pull products by `createdAt DESC`
=> Cart Updates - React Modal discontinued

client/components/DisplayAccountPage.js, client/components/DisplayRedWines.js, client/components/DisplaySingleProduct.js, client/components/forms/UpdateAccount.js, client/components/forms/UpdateAccountForm.js, server/api/users.js
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_
=> updated frontend for user account page and single product page

client/store/orderProducts.js, server/api/orders.js, server/index.js
routes on orders has been updated to partially suport sessions. Many lines are not dry, and feature a messy if else structure
=> guest exp partially working. Update and Delete do not work. Checkout redirect not hooked up.

server/api/routeProtections.js, server/api/users.js
Revised admin and user access to user routes.
=> revised admin and user access to user routes

server/api/orders.js, server/auth/index.js
see demo feature in slack. merges sessions cart to a user's preexisting cart.
=> WORKING mergeCartsessions

client/components/forms/SingleProductAddToCart.js, client/components/page/SingleProduct.js, client/components/page/module/ProductGridItem.js, client/index.js, package-lock.json, package.json
Using react-toast-notifications
Added on Single Products and All Products
=> Added Toasts

client/components/forms/SingleProductAddToCart.js
=> fixupaddtocart

client/components/forms/SingleProductAddToCart.js, client/components/page/SingleProduct.js
=> Implemented toasts!
